In [77]:
from tensorflow.keras.preprocessing.text import one_hot

In [78]:
### Sentences

sent=[
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good man",
    "I am a good developer",
    "Understand the meaning of words",
    "your videos are good"
]

In [79]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good man',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are good']

In [80]:
### Define the vocalbulary size
voc_size=10000

In [81]:
### One Hot representation
one_hot_representation=[one_hot(words,voc_size) for words in sent]

In [82]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good man',
 'I am a good developer',
 'Understand the meaning of words',
 'your videos are good']

In [83]:
one_hot_representation

[[4096, 5334, 1783, 6355],
 [4096, 5334, 1783, 359],
 [4096, 6434, 1783, 4032],
 [6912, 2443, 2633, 5944, 2099],
 [6912, 2443, 2633, 5944, 1319],
 [6519, 4096, 9318, 1783, 4119],
 [7196, 508, 2978, 5944]]

In [84]:
### Word embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [85]:
import numpy as np

In [86]:
### Notice how the sentences are of different lengths. 
### We have to convert them to the same length.

In [87]:
### setting the sentences length. lets say, 8 for this example
sent_length=8
embedded_docs=pad_sequences(one_hot_representation,padding="pre",maxlen=sent_length)
### pad_sequences adds extra words to the sentences with "0" as vector to make all sentences of same length
### Used padding="pre" to add new words at the starting

In [88]:
print(embedded_docs)

[[   0    0    0    0 4096 5334 1783 6355]
 [   0    0    0    0 4096 5334 1783  359]
 [   0    0    0    0 4096 6434 1783 4032]
 [   0    0    0 6912 2443 2633 5944 2099]
 [   0    0    0 6912 2443 2633 5944 1319]
 [   0    0    0 6519 4096 9318 1783 4119]
 [   0    0    0    0 7196  508 2978 5944]]


In [89]:
### feature representation
dimension=10


In [90]:
# ...existing code...
model = Sequential()
model.add(Embedding(voc_size, dimension, input_length=sent_length))
model.compile("adam", "mse")
model.build(input_shape=(None, sent_length))
# ...existing code...

In [91]:

model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [93]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[[-0.02459967, -0.02564791,  0.03500619, -0.03552053,
          0.03709425, -0.02436758, -0.04451232, -0.04523405,
         -0.02663854,  0.00502753],
        [-0.02459967, -0.02564791,  0.03500619, -0.03552053,
          0.03709425, -0.02436758, -0.04451232, -0.04523405,
         -0.02663854,  0.00502753],
        [-0.02459967, -0.02564791,  0.03500619, -0.03552053,
          0.03709425, -0.02436758, -0.04451232, -0.04523405,
         -0.02663854,  0.00502753],
        [-0.02459967, -0.02564791,  0.03500619, -0.03552053,
          0.03709425, -0.02436758, -0.04451232, -0.04523405,
         -0.02663854,  0.00502753],
        [-0.03595384, -0.01876053, -0.03810672, -0.00275856,
          0.01907423,  0.02747587,  0.02211806,  0.03993453,
          0.00660019, -0.03954817],
        [-0.04550476, -0.00224384, -0.04849559, -0.01883819,
         -0.03564442,  0.01804591,  0.04509518,  0.01748078,
         -0.01827919,  0.04000911],
        [ 0.03652234, -0.03740931,  0.01506737,  0.0

In [94]:
embedded_docs[0]

array([   0,    0,    0,    0, 4096, 5334, 1783, 6355], dtype=int32)

In [96]:
model.predict(embedded_docs[:1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


array([[[-0.02459967, -0.02564791,  0.03500619, -0.03552053,
          0.03709425, -0.02436758, -0.04451232, -0.04523405,
         -0.02663854,  0.00502753],
        [-0.02459967, -0.02564791,  0.03500619, -0.03552053,
          0.03709425, -0.02436758, -0.04451232, -0.04523405,
         -0.02663854,  0.00502753],
        [-0.02459967, -0.02564791,  0.03500619, -0.03552053,
          0.03709425, -0.02436758, -0.04451232, -0.04523405,
         -0.02663854,  0.00502753],
        [-0.02459967, -0.02564791,  0.03500619, -0.03552053,
          0.03709425, -0.02436758, -0.04451232, -0.04523405,
         -0.02663854,  0.00502753],
        [-0.03595384, -0.01876053, -0.03810672, -0.00275856,
          0.01907423,  0.02747587,  0.02211806,  0.03993453,
          0.00660019, -0.03954817],
        [-0.04550476, -0.00224384, -0.04849559, -0.01883819,
         -0.03564442,  0.01804591,  0.04509518,  0.01748078,
         -0.01827919,  0.04000911],
        [ 0.03652234, -0.03740931,  0.01506737,  0.0